spring.application.name=PowerUp
spring:
  #  h2:
  #    console:
  #      enabled: true
  datasource:
    url: jdbc:oracle:thin:@oracle.fiap.com.br:1521:orcl
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
